
import Footer from '@/components/footer'
import './globals.css'
import Navbar from '@/components/navbar'
import Carousel from '@/components/carousel'
import { SCRIPT_DATA } from '@/utils/constant'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src={SCRIPT_DATA} defer />
      </head>
      <body>
      <Navbar/>
      <Carousel/>
      {children}
      <Footer/>
      
      </body>
    </html>
  )
}
